title: HCI Systematic Review-lution 
description: A landing page and collection of resource for a movement towards more rigorous and useful systematic reviews in human-computer interaction (HCI).
remote_theme: just-the-docs

baseurl: "/sysreviewlution"
url: https://ajkt.github.io

