title: HCI Systematic Review-lution 
description: A landing page and collection of resources for a movement towards more rigorous and useful systematic reviews in human-computer interaction (HCI).
theme: jekyll-theme-minimal

url: https://ajkt.github.io/sysreviewlution

