title: HCI Systematic Review-lution 
description: A landing page and collection of resource for a movement towards more rigorous and useful systematic reviews in human-computer interaction (HCI).
theme: just-the-docs

url: https://ajkt.github.io/sysreviewlution

